;  Demo..
;   CPDR	 hafizanin 120h adresinden itibaren adresi bir azaltarak
;		  30h sayisini ara.. (100 defa deneme sansi var.)
;		  Bulunursa 200h adresine datanin bulundugu adresi yaz.
;		  Bulunamazsa 200h'a sifir(word) yaz.
;
	.dfb	$100,$10,$20,$30,$40
        ;            100 101 102 103

	.org	$300
	ld	hl,$120
	ld	bc,#100
	ld	a,$30

	cpdr			; block arama komutu..
	jp	z,BULUNDU

        ld      hl,$0		; bulunmadiysa.

BULUNDU:
	ld	($200),hl
CIK:	halt

